name: Build, test and deploy

on:
  push:
    branches: [main]

jobs:
  build_and_deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - run: dotnet restore

      - run: dotnet test tests/tests.csproj -c Release
        env:
          ASPNETCORE_ENVIRONMENT: Testing

      - run: dotnet publish src/web/web.csproj -c Release --output ./publish --no-restore

      - name: Generate appsettings.Production.json
        shell: pwsh
        run: |
          $config = @"
          {
            "Jwt": {
              "Key": "${{ secrets.JWT_KEY }}"
            }
          }
          "@
          $config | Out-File -FilePath ./publish/appsettings.Production.json -Encoding utf8

      - name: Install Web Deploy
        run: |
          if (-not (Test-Path "C:\Program Files (x86)\IIS\Microsoft Web Deploy V3\msdeploy.exe")) {
            choco install webdeploy -y --no-progress
          }
        shell: pwsh

      - name: Deploy to MonsterASP.NET via WebDeploy
        uses: rasmusbuchholdt/simply-web-deploy@2.1.0
        with:
          website-name: ${{ secrets.WEBSITE_NAME }}
          server-computer-name: ${{ secrets.SERVER_COMPUTER_NAME }}
          server-username: ${{ secrets.SERVER_USERNAME }}
          server-password: ${{ secrets.SERVER_PASSWORD }}
